# Generated by Django 4.1 on 2022-08-24 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("crbs", "0002_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="comment",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("room", "date")},
        ),
    ]
